import{i as d,S as u}from"./assets/vendor-8cfa25bd.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))n(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const i of r.addedNodes)i.tagName==="LINK"&&i.rel==="modulepreload"&&n(i)}).observe(document,{childList:!0,subtree:!0});function a(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function n(e){if(e.ep)return;e.ep=!0;const r=a(e);fetch(e.href,r)}})();document.addEventListener("DOMContentLoaded",function(){var c=document.getElementById("search-form"),t=document.getElementById("loader"),a=document.querySelector(".gallery");c.addEventListener("submit",function(n){n.preventDefault();var e=c.querySelector('input[name="searchQuery"]').value.trim();if(e===""){d.error({title:"Error",message:"Please enter a search query.",position:"topRight"});return}t.classList.remove("hidden"),a.innerHTML="";var r="45260330-4aac6e6a6c993f9154e4b36c5",i="https://pixabay.com/api/?key="+r+"&q="+encodeURIComponent(e)+"&image_type=photo&orientation=horizontal&safesearch=true&per_page=12&page=1";fetch(i).then(s=>s.json()).then(s=>{if(t.classList.add("hidden"),s.totalHits>0){s.hits.forEach(o=>{var l=document.createElement("div");l.className="photo-card",l.innerHTML=`
              <a href="${o.largeImageURL}" class="gallery-link">
                <img src="${o.previewURL}" alt="${o.tags}" loading="lazy" />
              </a>
              <div class="info">
                <p class="info-item"><b>Likes</b> ${o.likes}</p>
                <p class="info-item"><b>Views</b> ${o.views}</p>
                <p class="info-item"><b>Comments</b> ${o.comments}</p>
                <p class="info-item"><b>Downloads</b> ${o.downloads}</p>
              </div>
            `,a.appendChild(l)});var m=new u(".gallery a");m.refresh()}else d.error({title:"No results",message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight",timeout:5e3})}).catch(s=>{t.classList.add("hidden"),console.error("Request Failed:",s),d.error({title:"Error",message:"An error occurred while fetching images.",position:"topRight",timeout:5e3})})})});
//# sourceMappingURL=commonHelpers.js.map
